n1 = input('digite algo: ')
print('\033[0;33;40m o tipo desse valor é ', type(n1))
print(' é um numero ? ', n1.isnumeric())
print(' É alfabético ? ', n1.isalpha(),'\033[35;40m')
print(' só tem espaço ? ', n1.isspace())
print(' é alfanumérico ? ', n1.isalnum())
print(' esta em maiúsculas ? ', n1.isupper())
print(' esta em minúsculas ? ', n1.islower())
print(' está capitalizada? ', n1.istitle(), '\033[m')
